#!/bin/sh
# secure-wp-config.sh - Secure wp-config.php generation
# Generates WordPress configuration without exposing credentials in process list

set -euo pipefail

# Load dependencies
# Note: SCRIPT_DIR is inherited from the calling script (install-wordpress.sh)
# If called directly, define it
if [ -z "${SCRIPT_DIR:-}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

# Load colors and logger if not already loaded
if [ -z "${COLORS_LOADED:-}" ]; then
    . "${SCRIPT_DIR}/lib/colors.sh"
fi
if [ -z "${LOGGER_LOADED:-}" ]; then
    . "${SCRIPT_DIR}/lib/logger.sh"
fi

# Generate wp-config.php securely
# Usage: generate_wp_config "db_name" "db_user" "db_pass" "db_host" "db_prefix" "target_dir"
# This function creates wp-config.php without passing credentials as WP-CLI arguments
generate_wp_config() {
    local db_name="$1"
    local db_user="$2"
    local db_pass="$3"
    local db_host="$4"
    local db_prefix="$5"
    local target_dir="$6"

    log_info "Generating secure wp-config.php..."

    # Create temporary file with restrictive permissions
    local temp_config=$(mktemp)
    chmod 600 "$temp_config"

    # Ensure cleanup on exit
    trap "rm -f $temp_config" EXIT INT TERM

    # Generate secure random keys and salts
    local keys_salts
    if command -v curl >/dev/null 2>&1; then
        keys_salts=$(curl -sSL https://api.wordpress.org/secret-key/1.1/salt/)
    else
        log_warn "curl not available, using basic random keys (less secure)"
        keys_salts=$(generate_basic_keys)
    fi

    # Write wp-config.php content to temporary file
    cat > "$temp_config" <<'EOF'
<?php
/**
 * WordPress Configuration File
 * Generated by WP Adjuvans Starter Kit
 * @link https://wordpress.org/documentation/article/editing-wp-config-php/
 */

// ** Database Settings ** //
EOF

    # Add database configuration (using single quotes to prevent variable expansion in heredoc)
    cat >> "$temp_config" <<EOF
define( 'DB_NAME', '${db_name}' );
define( 'DB_USER', '${db_user}' );
define( 'DB_PASSWORD', '${db_pass}' );
define( 'DB_HOST', '${db_host}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**
 * WordPress Database Table prefix.
 */
\$table_prefix = '${db_prefix}';

/**
 * Authentication Unique Keys and Salts.
 * @link https://api.wordpress.org/secret-key/1.1/salt/
 */
${keys_salts}

/**
 * WordPress debugging mode.
 * Enable for development, disable in production.
 */
define( 'WP_DEBUG', false );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );

/**
 * Custom log file location (outside web root for security)
 */
if ( WP_DEBUG_LOG ) {
    if ( ! defined( 'WP_DEBUG_LOG_FILE' ) ) {
        define( 'WP_DEBUG_LOG_FILE', dirname( __FILE__ ) . '/../logs/' . date( 'Y-m-d' ) . '_wp-errors.log' );
    }
    ini_set( 'error_log', WP_DEBUG_LOG_FILE );
}

/**
 * Security enhancements
 */
define( 'DISALLOW_FILE_EDIT', true );        // Disable file editor in admin
define( 'FORCE_SSL_ADMIN', false );          // Enable this if you use SSL
define( 'AUTOMATIC_UPDATER_DISABLED', false ); // Allow automatic updates

/**
 * Absolute path to the WordPress directory.
 */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
EOF

    # Ensure target directory exists
    if [ ! -d "$target_dir" ]; then
        log_info "Creating target directory: ${target_dir}"
        mkdir -p "$target_dir" || {
            log_error "Failed to create directory: ${target_dir}"
            return 1
        }
    fi

    # Move temporary file to target location
    local config_path="${target_dir}/wp-config.php"
    mv "$temp_config" "$config_path"

    # Set restrictive permissions (read-only for owner, no access for group/others)
    chmod 400 "$config_path"

    log_success "wp-config.php created securely at ${config_path}"
    log_info "File permissions: 400 (read-only)"

    return 0
}

# Generate basic random keys if curl is not available
# This is a fallback and less secure than WordPress.org API
generate_basic_keys() {
    local keys="AUTH_KEY SECURE_AUTH_KEY LOGGED_IN_KEY NONCE_KEY AUTH_SALT SECURE_AUTH_SALT LOGGED_IN_SALT NONCE_SALT"

    for key in $keys; do
        # Generate 64 character random string using /dev/urandom
        local random_key=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*()_+{}|:<>?~' </dev/urandom | head -c 64)
        echo "define( '${key}', '${random_key}' );"
    done
}

# Update existing wp-config.php with new credentials (use with caution)
# Usage: update_wp_config_credentials "db_name" "db_user" "db_pass" "config_path"
update_wp_config_credentials() {
    local db_name="$1"
    local db_user="$2"
    local db_pass="$3"
    local config_path="$4"

    if [ ! -f "$config_path" ]; then
        log_error "Config file not found: $config_path"
        return 1
    fi

    log_warn "Updating wp-config.php credentials..."

    # Create temporary file
    local temp_config=$(mktemp)
    chmod 600 "$temp_config"
    trap "rm -f $temp_config" EXIT INT TERM

    # Update database credentials using sed
    sed -e "s/define( *'DB_NAME'.*/define( 'DB_NAME', '${db_name}' );/" \
        -e "s/define( *'DB_USER'.*/define( 'DB_USER', '${db_user}' );/" \
        -e "s/define( *'DB_PASSWORD'.*/define( 'DB_PASSWORD', '${db_pass}' );/" \
        "$config_path" > "$temp_config"

    # Replace original file
    mv "$temp_config" "$config_path"
    chmod 400 "$config_path"

    log_success "wp-config.php credentials updated"
    return 0
}

# Validate wp-config.php syntax
# Usage: validate_wp_config "path/to/wp-config.php"
validate_wp_config() {
    local config_path="$1"

    if [ ! -f "$config_path" ]; then
        log_error "Config file not found: $config_path"
        return 1
    fi

    # Check PHP syntax
    if command -v php >/dev/null 2>&1; then
        if php -l "$config_path" >/dev/null 2>&1; then
            log_success "wp-config.php syntax is valid"
            return 0
        else
            log_error "wp-config.php syntax error detected"
            return 1
        fi
    else
        log_warn "PHP not available, cannot validate syntax"
        return 0
    fi
}
